# Generated by Django 4.2.1 on 2023-05-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=20)),
            ],
        ),
    ]
