version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: welcome
      POSTGRES_HOST: localhost

    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./:/app

    ports:
      - '8000:8000'
    depends_on:
      - db
    links:
      - db
 
volumes:
  db-data:
 